# -*- coding: utf-8 -*-
"""1. Methods of fillna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s702Y7ycBgF3vyAZpKjQZxo44wGUT2IX

#Methods of Panda
#Pandas Dropna()       Parameter:
                       axis
                       how
                       thresh
                       subset
                       inplace

#What is Pandas fillna?
Fillna fills the NaN values with given values (input)
#Syntax:
Dataframe.fillna()
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv')
df

df.fillna(0)

"""It fill values with 0 whereever the NaN values

#Now with 2
"""

df.fillna(2)

"""#Now, substitute t NaN values with appropriate replacement  differen values through the Dictionar"""

df.fillna({'Tweet':'none', 'Label':'joy', 'value':0})

"""#Now forward values fill by using method ffill
Means it fill the previous values inside the dataset
"""

df.fillna(method='ffill')

"""#We can use pad in place of ffill
It will also fill the previous value

"""

df.fillna(method='pad')

"""#Now we fill the backward values by using the method bfill

"""

df.fillna(method='bfill')

