# -*- coding: utf-8 -*-
"""1. Methods of fillna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s702Y7ycBgF3vyAZpKjQZxo44wGUT2IX

#Methods of Panda
#Pandas Dropna()       Parameter:
                       axis
                       how
                       thresh
                       subset
                       inplace

#What is Pandas fillna?
Fillna fills the NaN values with given values (input)
#Syntax:
Dataframe.fillna()
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv')
df

df.fillna(0)

"""It fill values with 0 whereever the NaN values

#Now with 2
"""

df.fillna(2)

"""#Now, substitute t NaN values with appropriate replacement  differen values through the Dictionar"""

df.fillna({'Tweet':'none', 'Label':'joy', 'value':0})

"""#Now forward values fill by using method ffill
Means it fill the previous values inside the dataset
"""

df.fillna(method='ffill')

"""#We can use pad in place of ffill
It will also fill the previous value

"""

df.fillna(method='pad')

"""#Now we fill the backward values by using the method bfill

"""

df.fillna(method='bfill')

"""#Now using method axis on index 0 means row index 1 means column
With it we have to specify the values or method otherwise it gives an error
"""

df.fillna(method='bfill',axis=0)
#it is for the backward row

#backward column
df.fillna(method='bfill',axis=1)

#forward row
df.fillna(method='ffill',axis=0)

#forward column
df.fillna(method='ffill',axis=1)
#

"""#Now we use the limit and it will be used when you have to fill the specific NaN values like 3 or 4 or 5

Syntax:
df.fillna(row, limit=values)
"""

df.fillna(0,limit=2)

# Now using method
df.fillna(method='ffill',limit=2)

"""#Now using the inplace which gives boolean result True or False
df.fillna(5, inplace=True) it replace 5 value where's the missing values present
"""

df.fillna(5,inplace=True)
df

df.fillna(6, inplace=False)
df

