# -*- coding: utf-8 -*-
"""2. replace function P-12 ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-HKL9llJNoCg9fDkPBgSDLOwzFKDpxM_

#Part 12
# We use the replace function
# What is Replace Function?
Values to the dataframes  are replaced with other values dynamically
#Synatx :
Dataframe.replace()

#Parameters:
1. to_replace
2. value
3. inplace
4. limit
5. rigix
6. method
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv')
df

df.replace(to_replace='tennis',value='cricket')

"""#We can use them without parameter names as well"""

df.replace('tennis','vollyball')

"""# Now we can replace the interger values as well like ID numbers without parameters name"""

df.replace(2,12)

"""# Through Parameters name"""

df.replace(to_replace=0, value=100)

"""# Now we can change all values of ID column with single value"""

df.replace ([0,1,2,3,4,5,6,7,8,9],0)

"""#Using Parameters"""

df.replace (to_replace =[0,1,2,3,4,5,6,7,8,9], value=0)

"""#We can Also replace with them by using the list by using with parameters

"""

df.replace (to_replace=[0,1,2,3,4,5,6,7,8,9], value=[11,22,33,44,55,66,77,88,99,100])

"""# Through list without using the parameters"""

df.replace ([0,1,2,3,4,5,6,7,8,9],[11,21,31,41,51,61,71,81,91,10])

"""# If we want to replace the specific column value we use the dictionary
Syntax:
df.replace({''column name':'value'}, 'replace with')
"""

df.replace({'Date':'No'}, 'False')

"""# Now we can replace the patterns through strings with integer value zero"""

df.replace('[A-Za-z]',0)

"""# It looks similar nothing has changed because we have to change the string
# So we use regex method which takes the boolean values and then replace strings into integera
"""

df.replace('[A-Za-z]',0, regex= True)

"""# if we want to replace an specific column values so we use the list"""

df.replace ({'Names':'[A-Za-z]'}, 'Awais', regex = True)

