# -*- coding: utf-8 -*-
"""3. Interpolate methods .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEbyLR4MPVTHdFCsJMrGwB2B6ZYa13a3

#P-13
#Interpolate methods

#parameters:
1. method          2. inplace
3. axis            4. limit_direction
5. limit           6. limit_area
#What is Pandas interpolate ?
Pandas interpolate () function is basically used to fill NaN values in dataframe or series
_very powerful function
_Uses various interpolation techniques
#Syntax:
Dataframe.interpolate()
or
Series.interpolate()
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv')
df

df.interpolate() #this fills only numeric values

df.interpolate(method='linear')

#replace the date with time
df.interpolate(method='time')

#check its type
type(df.Date[0])

#Change data type
df=pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv',parse_dates=['Date'])
df

type(df.Date[0])

#Make date column a index column
df=pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv',parse_dates=['Date'], index_col=['Date'])
df

df.interpolate(method='time')

#Now use method parameter index
df.interpolate(method='index')

df=pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv',parse_dates=['Date'], index_col=['Profits'])
df

