# -*- coding: utf-8 -*-
"""Slicing  Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lb6jnKXNWIgWGThppbR8xGgtNx9qykQa

**Muhammad Awais Practice code**

**All Silicing Numpy**
"""

# Array Matrix 10 by 10
import numpy as np
arr10=np.arange(1,101).reshape(10,10)
print(" The Original Result of 10 by 10 array = \n", arr10)

# Find value of index [0,0] mean[row, column]
print(arr10[0,0])

# check the output dimension
print(arr10[0,0].ndim)

# Execute single row of array
print(" 1d array  row = ",arr10[0])

#Check its dimension
print("check dimension of 1d array  row  ",arr10[0].ndim)

# Check its column 1d
print("Check dimesnion of the 1d array Column \n",arr10[:,0])

#Given Column convert into 2d array
print("Given Column convert into 2d array \n",arr10[:,0:1])

# Now verify its dimension
print("its dimesion = ",arr10[:,0:1].ndim)

# Call again Complete array
print("Call again Complete array \n",arr10)

# Now we access its 2d ,3rd, 4th rows and respectively columns. Synatx[row start: row end, col start:col End]
print("Now we access its 2d ,3rd, 4th rows and respectively columns \n",arr10[1:4,1:4])
print("\n it has designed 3x3 matrix")

# Execute complete row and 2nd and 3rd col indexes values into 2d array
print("Execute complete row and 2nd and 3rd col indexes values \n",arr10[:,1:3])

# Access complete matrix by using 2 slices operator
print("Result of Complete array = \n ",arr10[:,:])

# another method to access complete matrix by using 2 slicing operator
print("Result of Complete array = \n ",arr10[::])

# Find
# How many spaces we keep to store items/attributes in array
print("keep spaces to store items = ",arr10.itemsize)

# matrix data type
print("Data Type of array = ", arr10.dtype)

#anothe method to find its spaces
# datatype bits / bits   Now

64/8

