# -*- coding: utf-8 -*-
"""Numpy Trigonometry Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSx2xSeLRpYG_Ch5ECdbuzbqS9vvmG_-

**Muhammad Awais**

**Numpy Trigonometry Functions such sin(), cos(), tan()...**
"""

import numpy as np

# Find sin 180 value
np.sin(180)

print("another method to print val of \n Sin 180 = ",np.sin(180))

# Cos 180 val
print(np.cos(180))

# Tan 180 val
print (np.tan(180))



"""**Now Plot their values. Mean Visulaized their values graph by importing matplot library**"""

# By matplotlib
import matplotlib.pyplot as plt

# for Graph visualization we need x and y values
# Now print x_sin values
x_sin =np.arange(0, 3*np.pi, 0.1)
print(x_sin)

# Now y-Sin values print
y_sin=np.sin(x_sin)
print(y_sin)

"""**Plotting both x-sin, y_sin values**"""

plt.plot(x_sin, y_sin)
plt.show()

"""**Cos plot here**"""

x_cos =np.arange(0, 3*np.pi, 0.3)
print(x_cos)

y_cos =np.arange(0, 3*np.pi, 0.3)
print(y_cos)

"""**Now plot x_cos and y_cos values graph**"""

plt.plot(x_cos,y_cos)
plt.show()

"""**Tan Graph visualize shortly**"""

x_tan=np.arange(0, 3*np.pi, 0.1)
y_tan=np.tan(x_tan)
plt.plot(x_tan,y_tan)
plt.show()

"""**Take ratios values in radian**"""

np.sin(180 * np.pi / 180)

