# -*- coding: utf-8 -*-
"""Numpy Array  Concatenation & Splits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17EaJkuFrr5vx1dP0lVztxPd-DDQbm1Kx

**Made By Muhmmad Awais Bhan**

**Numpy Array Concatenation & Splits**
"""

# make an array 4 by 4 matrix
import numpy as np
arr1=np.arange(1,17).reshape(4,4)
print("Result of 4 by 4 array = \n ",arr1)

# make another array 4 by 4 matrix
arr2=np.arange(17,33).reshape(4,4)
print("Result of 4 by 4 array = \n ",arr2)

# Now Concatenate both Arrays
Con=np.concatenate((arr1,arr2))
print("Concatenated Arrays = \n ", Con)

# Now Concatenate Row wise
Rcon =np.concatenate((arr1,arr2), axis=1)
print("Row wise Concatenated \n", Rcon)

# Concatenate Vertically arr1 and arr2
Vcon=np.vstack((arr1,arr2))
print("Vertically Concatenated both arrays \n ", Vcon)

#Concatenate Horixentally arr1 and arr2
Hcon=np.hstack((arr1,arr2))
print("Horizontally Concatenated both arrays \n ", Hcon)

# another method
np.hstack((arr1,arr2))

"""**To Break Array by using Split**"""

# Structure to split np.split(array,parts)
#Break Arr1 into 2 parts
np.split(arr1,2)

# Store splited array into list
list1 =np.split(arr1,2)

# Check its type
type(list1)

# value of that list on index
list1[0]

print ("it gives the array because array has been stored inside the list in previous section")

# Check type of list index 0
type(list1[0])

"""**Break Array Column-wise**"""

np.split(arr1,2, axis=1)



"""**Create  1d array then Split it into Multi-array**"""

d1= np.array([4,7,1,5,6,])

# Now split it into multiple dimensions using a list:
# – the 1st array should contain the element 4
# – the 2nd array should contain the elements 7,1,
# – and the 3rd array should contain all the remaining elements 5,6.
np.split(d1,[1,3])

