# -*- coding: utf-8 -*-
"""Pandas Dataframes .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_M5b5lGyMm-aBpG-hdkyCywMVhD23o6P

**How to create Pandas Datafames in python**
"""

import pandas as pd

"""create empty dataframe"""

emp_df=pd.DataFrame()
print(emp_df)

"""create a list variable"""

list = ['a','b','c','d']
print(list)

"""With the help of list create dataframes"""

df1=pd.DataFrame(list)
print(df1)

"""Make list of list"""

list_of_list=[[1,2,3],[4,5,6],[7,8,9]]
print (list_of_list)

"""With the help of list of list craete datframes"""

df2 =pd.DataFrame(list_of_list)
print(df2)

"""create a dictionary of list
Syntax dic ={'key': [list]}         key is use as a column name
"""

dict={'id':[1,2,3,4,5,6]}

dict

"""Create Dataframes by using dictionary"""

df3=pd.DataFrame(dict)
print(df3)

"""make more id's of the dictionary"""

dic2={'id1':[1,2,3,4], 'id2':[5,6,7,8]}
print(dic2)

"""Nw make its Dataframes"""

df4=pd.DataFrame(dic2)
print(df4)

"""Create list of dictionaries and make its Dataframes"""

ls_dic=[{'a':1, 'b':2},{'a':5, 'b':10}]
df5=pd.DataFrame(ls_dic)
print(df5)

"""create with differeny keys"""

ls_dic=[{'a':1, 'b':2},{'x':5, 'y':10}]
df5=pd.DataFrame(ls_dic)
print(df5)

"""make un equal dictionaries"""

ls2_dic= [{'a':1,'b':2,'c':3},{'a':4,'b':5}]
df6=pd.DataFrame(ls2_dic)
print(df6)

"""Create Dictionary of series"""

dic_sr={'id':pd.Series([1,2,3,4,5]), 'sn':[111,222,333,444,555]}
print(dic_sr)

"""Now convert it into Dataframes"""

df7=pd.DataFrame(dic_sr)
print(df7)

