# -*- coding: utf-8 -*-
"""2. Read CSV File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WmEBfYlDL9H3UHQbIjzH5ZvV81d4cy3C

**How to read CSV file**
"""

import pandas as pd

help(pd.read_csv)

"""**Before read to it it must be import from available directory**"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv')
df.head()

"""**Find where this Dataframe has been stored we can find by using the os**"""

import os

print(os.getcwd())

