# -*- coding: utf-8 -*-
"""4. Part 2 write Pandas csv file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DbuUkGb-J4q-dhRRhRKbbXLPe2t4Kew8

**Part 2 Pandas CSV file write**
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv')
df.head()

"""To make Fisrt row as header by using header parameter with the index"""

df=pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', header=1)
df

"""Make 3rd row as header"""

df=pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', header=2)
df

"""Make header none"""

df=pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv',header=None)
df

"""To customize header with any name by using prefix parametr but there should header = None used along with it other Prefix parameter dosen't work proper"""

# For Jupyter Notebook method
# df=pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', header=None, prefix='Col')
# df

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', header=None)
df = df.add_prefix("Col")
df

"""Giving name to each column by using names parameter"""

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', names=['A','Awais','B'])
df