# -*- coding: utf-8 -*-
"""6.Handling Missing Values ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JrbdGy_8n8sY8Le2ibzQPvsFlOrwsc0_

#Python Pandas P-8
#Handling Missing Values

# we cover the following topics
1. na_values
2. Keep_default_na
3. na_filter
"""

from google.colab import drive

# Mount your Google Drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv')
df

"""**Now handle missing/ Null values**



"""

df

df

"""it does not consider the not available as na so we use the na_values parameter for this"""

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv',na_values='not available')
df