# -*- coding: utf-8 -*-
"""6.Handling Missing Values ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JrbdGy_8n8sY8Le2ibzQPvsFlOrwsc0_

#Python Pandas P-8
#Handling Missing Values

# we cover the following topics
1. na_values
2. Keep_default_na
3. na_filter
"""

from google.colab import drive

# Mount your Google Drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv')
df

"""**Now handle missing/ Null values**



"""

df

df

"""it does not consider the not available as na so we use the na_values parameter for this"""

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv',na_values='not available')
df

"""I put the missing value in dataset as the no values"""

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv',na_values='not available')
df

"""Its result is no values so we consider it as NaN so we use the list for considering multiple values as NaN"""

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv',na_values=['not available','no values '])
df

"""# If we want to it does not show the Null all the below Parameterw
#All These Strings Are Considered as Default NaN Values by Pandas

#N/A        -NaN        null
#N/A N/A    -nan        n/a
#NA         N/A         nan
-1.#IND     NA          1.#IND
-1.#QNAN    NULL        1.#QNAN




**SO we use the keep_default_na      Parameter** then print it

"""

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv',keep_default_na=False)
df

"""#If we make the keep_default_na = true
then it will show below result
"""

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv',keep_default_na=True)
df

"""It consider all other as NaN excluding the n values and not avaible just put both of them similar

#Now If we want the no any value will be missing in our data set so we use na_filter which increase its performance
"""

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv',na_filter=False)
df

