# -*- coding: utf-8 -*-
"""7. Handling Missing Values P-9ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3RRPzERpyZ8yEpSDBbqruZNTiew-4F5

#Python Pandas P-9
#Handling Missing Values

# we cover the following topics
1. isnull()
2. notnull()
"""

from google.colab import drive

# Mount your Google Drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv')
df

"""#Now call the isnull values"""

df.isnull()

"""It gives false because no any value is null inside the data set
Now it gives the true some missing values inside the dataset

"""

df.isnull()

"""use sum () with isnull () that will some the all values which are present in any of the column"""

df.isnull().sum()

"""Now sum all the missing values sum
Like
"""

df.isnull().sum().sum()

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv')
df

"""#Now use the notnull() function  """

df.notnull()

"""It works ViceVersa of the isnull () it gives true while all data represents in cells and give the false when data is missing"""

