# -*- coding: utf-8 -*-
"""7. Handling Missing Values P-9ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3RRPzERpyZ8yEpSDBbqruZNTiew-4F5

#Python Pandas P-9
#Handling Missing Values

# we cover the following topics
1. isnull()
2. notnull()
"""

from google.colab import drive

# Mount your Google Drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv')
df