# -*- coding: utf-8 -*-
"""Handling Missing Values P-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r50o_2Fpjlwou5XamrJjC2Tw1VhJMmyG

#Handling Missing Values P-10
"""

from google.colab import drive

# Mount your Google Drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv')
df

"""# NaN represents missing values in the dataset.
# The dropna() method (df.dropna()) removes missing values.
# It returns a new DataFrame without NaN values.

"""

df.dropna()

"""# In dropna(), the 'axis' parameter specifies rows or columns.
# axis=0 refers to rows, and axis=1 refers to columns.
# By default, axis=0 is used, so rows containing NaN values are removed.

# Now call as axis =1
"""

df.dropna(axis=1)

"""# In dropna(), the parameter after axis is 'how'.
# The 'how' parameter accepts two string values: 'any' and 'all'.
# 'any' drops rows or columns if at least one value is NaN.
# 'all' drops rows or columns only if all values are NaN.

"""

df.dropna(how='any')

df.dropna(how='all')

"""# apply how any on column"""

df.dropna(how='any', axis=1)

"""#apply on row dropna(how 'any')"""

df.dropna(how='any', axis=0)

