# -*- coding: utf-8 -*-
"""Handling Missing Values P-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r50o_2Fpjlwou5XamrJjC2Tw1VhJMmyG

#Handling Missing Values P-10
"""

from google.colab import drive

# Mount your Google Drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv')
df

"""NaN shown at Where's Missing Values
# dropna() method Syntax is df.dropna() and it creates new dataframe which has not NaN Values
#dropna remove missing Values

"""

df.dropna()

"""# In dropna () axis parameter used which has 0 & 1 input values
# 0 means row and 1 mean column
# By default values is 0: it removes bydefault that row which has NaN values

# Now call as axis =1
"""

df.dropna(axis=1)

