import numpy as np
Arr_d3=np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print("Three Dimension Array", Arr_d3)
print("Dimensionm of 3d Array", Arr_d3.ndim)
print("Shape of the 3d Array", Arr_d3.shape)
print("Size of the 3D Array",Arr_d3.size)
print("Data Type of 3D Array",Arr_d3.dtype)
print("Item size of 3D Array",Arr_d3.itemsize)
print("Type of 3D Array",type(Arr_d3))
print(np.ones((3,4,5),dtype=int))