# -*- coding: utf-8 -*-
"""3. Write Pandas CSv file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TwCPcZg2Jy0oZUUjarQmK1BEeWAjPVg4

**How to write Pandas CSV file**
"""

import pandas as pd

"""Before Write we read the CSV file"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv')
df.head()

"""Find its type"""

type(df)

"""Print its column Names"""

df.columns

"""print its single row by using nrow parameter"""

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', nrows=1)
df

"""Print its 5 row"""

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', nrows=5)
df

"""Now print columns by using usecols parameter like print id column so it will print through its index in list"""

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', usecols=[0])
df

"""Print its important Columns like id and labels"""

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', usecols=[0,2])
df

"""Skip any row of dataset by using skiprows parameter

Skip its first row
"""

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', skiprows=1)
df

"""Skip multiple rows by using index in list of the skiprows like 4,6"""

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', skiprows=[4,6])
df

"""print again dataset"""

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv')
df

"""Now make its column names in index shape like id by using the index_col parmeter"""

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', index_col="Id")
df

"""Now print the tweet column"""

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', index_col="Tweet")
df

"""We can also make them through their index number like for label index no is 2"""

df = pd.read_csv('/content/drive/MyDrive/datasets/tweet_emotions.csv', index_col=2)
df

