# -*- coding: utf-8 -*-
"""5.Parameters of read_csv Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175OrqrbRomtPE8H9kPbFW-sx8nuQ61xC

#Pyhton Pandas P-7
#How to Write CSV file in Pandas

**Parameters of read_csv Function in Pandas **
1. header               head()
2. prefix               tail()
3.names                 dtype
                        true_values
                        false_values
"""

from google.colab import drive

# Mount your Google Drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv')



df.head()

"""**Call by using head()**     It calls first 5 rows"""

df.head()

"""**Call 1 row by using head()** it calls first row from top"""

df.head(1)

"""**Call 8 row by using head() it calls first row from top**"""

df.head(8)

"""**tail() **it calls last five row from bottom"""

df.tail()

df.tail(8)

"""**Change Datatype an specific column by using dtype parameter**"""

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv',dtype={'ID':'float64'})
df.head()

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv',dtype={'ID':'float64', 'Profits':'float64'})
df

"""#True_Values Parameter use through the list []"""

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv')
df

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv', true_values=['yes'])
df

"""#False_Values Parameter use through the list []"""

df = pd.read_csv('/content/drive/MyDrive/datasets/bbc.csv', true_values=['yes'],false_values=['No'])
df

